### ISSUE TITLE
Change product name.

### ISSUE THREAD

**Issue by takagi** [takagi/lake#14]
Change the product name because it is likely confusing with clack especially on completion. Any good name?

The followings are also changed.
- GitHub title and description
- GitHub issues
- CircleCI
- Coveralls

**Comment by takagi** [comment]
@guicho271828 suggests http://dreamatico.com/data_images/cake/cake-5.jpg .

@fukamachi suggests [![lake](http://c2.staticflickr.com/4/3858/15177832392_8fcb77928e_k.jpg)](https://www.flickr.com/photos/davebloggs007/15177832392/in/photolist-nPf8v7-p8dmMo-oQL5kt-nFW3y2-nH2y82-f2528A-pddqL5-o3YZyC-4nVApo-3My9kM-qGgc4o-o74QBS-b6WbTn-suUmFP-cGbfgC-o2srY9-pcdTiq-hDTk4o-9YAm13-MZLmY-33Wgi-nZ26iF-prF8SN-kg9rxF-ptFvSU-bcghk6-btKLVe-p4uWhK-cM7Xk1-aSzLr-5ciNFo-bJG53t-dJBa8J-9LUCTe-oBD8Qs-e5Bq2g-nWwnkb-o768Uc-avkYEA-ijCbYn-che7fJ-7xDMeB-nDjjUN-q28xF4-dbmsVv-9DzCgN-7snLCu-qME3i-pvN5Fe-ds8tit)

**Comment by takagi** [comment]
@fukamachi 
Lake, **L**isp m**ake**, is reasonable. How often lack is primarily used compared with clack, because lack and lake might have the same issue as clack and clake? あ、clack と clake を並べるとほんとに見分けづらい。Four letters, or beginning with "lac..." / "lak..." might help in lake's case.

@guicho271828 
Cake, **C**ommon lisp m**ake**, is not so unreasonable, good.

**Comment by takagi** [comment]
@fukamachi says "Cake reminds me of [this](http://coffeescript.org/documentation/docs/cake.html)."

**Comment by takagi** [comment]
@fukamachi says
"Lake is also used by Lua. https://github.com/stevedonovan/Lake
We may need completely different naming."

**Comment by guicho271828** [comment]
Perhaps some innovation is required. Let's follow the line of "alien" "ufo" "roswell".
What reminds of making and building something, in SF literature?

**Comment by takagi** [comment]
I want the name of making monsters.

**Comment by takagi** [comment]
Or making aliens.

**Comment by guicho271828** [comment]
I looked up the list of cthulhu gods but they all are related to some sort of destruction --- no creation! (they are not aliens at all, btw)

**Comment by takagi** [comment]
lol
